<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class EventSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        DB::table('users')->updateOrInsert(
            ['email' => 'admin@gmail.com'],
            [
                'name' => 'Admin Organizer',
                'password' => Hash::make('123456'),
                'role' => 'organizer',
                'created_at' => $now,
                'updated_at' => $now,
            ]
        );

        $adminId = DB::table('users')->where('email', 'admin@gmail.com')->value('id');

        DB::table('events')->insert([
            [
                'organizer_id' => $adminId,
                'name' => 'Đêm nhạc Acoustic ven sông',
                'description' => 'Không gian âm nhạc nhẹ nhàng với các bản acoustic Việt Nam và quốc tế dành cho cộng đồng yêu nhạc.',
                'category' => 'Music',
                'location' => 'The Riverside Cafe, Đà Nẵng',
                'date_time' => '2026-06-12 19:00:00',
                'capacity' => 120,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Workshop Thiết kế UI cho người mới',
                'description' => 'Buổi thực hành về tư duy layout, màu sắc, typography và cách xây dựng giao diện web cơ bản.',
                'category' => 'Workshop',
                'location' => 'Innovation Hub, TP. Hồ Chí Minh',
                'date_time' => '2026-06-18 09:00:00',
                'capacity' => 60,
                'event_type' => 'Paid',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Bạn đã dùng Figma chưa?', 'Bạn mong muốn học kỹ năng nào?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Ngày hội chạy bộ cộng đồng',
                'description' => 'Sự kiện chạy bộ 5km dành cho mọi lứa tuổi nhằm khuyến khích lối sống năng động và lành mạnh.',
                'category' => 'Sports',
                'location' => 'Công viên Gia Định, TP. Hồ Chí Minh',
                'date_time' => '2026-06-21 06:00:00',
                'capacity' => 500,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Cỡ áo của bạn?', 'Bạn có vấn đề sức khỏe cần lưu ý không?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Talkshow AI trong giáo dục',
                'description' => 'Chia sẻ về cách ứng dụng AI vào học tập, giảng dạy và xây dựng kế hoạch phát triển kỹ năng.',
                'category' => 'Technology',
                'location' => 'Đại học Bách Khoa Hà Nội',
                'date_time' => '2026-06-25 14:00:00',
                'capacity' => 200,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Phiên chợ xanh cuối tuần',
                'description' => 'Không gian mua sắm sản phẩm thủ công, nông sản sạch và các hoạt động tái chế cho gia đình.',
                'category' => 'Community',
                'location' => 'Nhà Văn hóa Thanh Niên, TP. Hồ Chí Minh',
                'date_time' => '2026-06-27 08:00:00',
                'capacity' => 350,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Lớp học nấu món Việt hiện đại',
                'description' => 'Chef địa phương hướng dẫn nấu các món Việt quen thuộc theo phong cách trình bày hiện đại.',
                'category' => 'Food',
                'location' => 'Saigon Culinary Studio',
                'date_time' => '2026-07-03 18:30:00',
                'capacity' => 35,
                'event_type' => 'Paid',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Bạn có dị ứng thực phẩm nào không?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Triển lãm ảnh Thành phố trong tôi',
                'description' => 'Triển lãm ảnh ghi lại nhịp sống đô thị, con người và những góc nhìn thân thuộc của thành phố.',
                'category' => 'Art',
                'location' => 'Bảo tàng Mỹ thuật TP. Hồ Chí Minh',
                'date_time' => '2026-07-05 09:30:00',
                'capacity' => 180,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Khởi nghiệp xã hội: từ ý tưởng đến sản phẩm',
                'description' => 'Buổi meetup kết nối các nhóm dự án xã hội, mentor và nhà đầu tư thiên thần.',
                'category' => 'Meetup',
                'location' => 'Dreamplex Nguyễn Trung Ngạn',
                'date_time' => '2026-07-09 17:30:00',
                'capacity' => 90,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Bạn đang làm dự án trong lĩnh vực nào?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Cuộc thi lập trình Hack for Community',
                'description' => 'Cuộc thi 24 giờ dành cho sinh viên xây dựng giải pháp công nghệ phục vụ cộng đồng.',
                'category' => 'Competition',
                'location' => 'FPT Software Campus, Đà Nẵng',
                'date_time' => '2026-07-12 08:00:00',
                'capacity' => 160,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Tên đội của bạn?', 'Số thành viên trong đội?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Webinar Quản lý tài chính cá nhân',
                'description' => 'Chuyên gia tài chính chia sẻ cách lập ngân sách, tiết kiệm và xây dựng mục tiêu tài chính.',
                'category' => 'Webinar',
                'location' => 'Online',
                'date_time' => '2026-07-15 20:00:00',
                'capacity' => 1000,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Ngày hội sách và văn hóa đọc',
                'description' => 'Hoạt động trao đổi sách, giao lưu tác giả trẻ và workshop xây dựng thói quen đọc.',
                'category' => 'Education',
                'location' => 'Đường sách Nguyễn Văn Bình',
                'date_time' => '2026-07-19 08:30:00',
                'capacity' => 300,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Festival Ẩm thực đường phố',
                'description' => 'Sự kiện quy tụ các gian hàng món ăn địa phương, âm nhạc ngoài trời và hoạt động gia đình.',
                'category' => 'Festival',
                'location' => 'Công viên 23/9, TP. Hồ Chí Minh',
                'date_time' => '2026-07-24 16:00:00',
                'capacity' => 800,
                'event_type' => 'Paid',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Lớp Yoga sáng chủ nhật',
                'description' => 'Buổi yoga ngoài trời phù hợp cho người mới bắt đầu, tập trung vào thở và giãn cơ.',
                'category' => 'Sports',
                'location' => 'Công viên Lê Văn Tám',
                'date_time' => '2026-07-26 06:30:00',
                'capacity' => 80,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Bạn có cần mượn thảm tập không?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Seminar Cloud Computing căn bản',
                'description' => 'Giới thiệu nền tảng điện toán đám mây, kiến trúc triển khai và các case study thực tế.',
                'category' => 'Technology',
                'location' => 'VNG Campus',
                'date_time' => '2026-07-30 13:30:00',
                'capacity' => 150,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Workshop Kỹ năng thuyết trình',
                'description' => 'Thực hành xây dựng nội dung, trình bày slide và kiểm soát giọng nói trước đám đông.',
                'category' => 'Workshop',
                'location' => 'PNV Training Center, Đà Nẵng',
                'date_time' => '2026-08-02 09:00:00',
                'capacity' => 45,
                'event_type' => 'Paid',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Bạn muốn cải thiện điểm nào khi thuyết trình?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Giao lưu tình nguyện viên mùa hè',
                'description' => 'Kết nối các nhóm tình nguyện, chia sẻ kinh nghiệm tổ chức hoạt động và tuyển thành viên mới.',
                'category' => 'Community',
                'location' => 'Cung Văn hóa Lao động TP. Hồ Chí Minh',
                'date_time' => '2026-08-06 18:00:00',
                'capacity' => 220,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Đêm phim ngoài trời',
                'description' => 'Buổi chiếu phim cộng đồng với khu vực picnic, đồ ăn nhẹ và thảo luận sau phim.',
                'category' => 'Entertainment',
                'location' => 'Sala Park, TP. Hồ Chí Minh',
                'date_time' => '2026-08-09 19:00:00',
                'capacity' => 250,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Bootcamp React trong 1 ngày',
                'description' => 'Lớp học chuyên sâu giúp người tham dự xây dựng một ứng dụng React hoàn chỉnh từ đầu.',
                'category' => 'Technology',
                'location' => 'CodeGym Hà Nội',
                'date_time' => '2026-08-15 08:30:00',
                'capacity' => 70,
                'event_type' => 'Paid',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Bạn đã học JavaScript bao lâu?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Ngày hội định hướng nghề nghiệp',
                'description' => 'Các diễn giả từ nhiều ngành chia sẻ lộ trình nghề nghiệp, kỹ năng cần có và cơ hội thực tập.',
                'category' => 'Education',
                'location' => 'Trung tâm Hội nghị White Palace',
                'date_time' => '2026-08-22 08:00:00',
                'capacity' => 400,
                'event_type' => 'Free',
                'status' => 'published',
                'require_additional_info' => true,
                'custom_form_spec' => json_encode(['questions' => ['Ngành nghề bạn quan tâm?']]),
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'organizer_id' => $adminId,
                'name' => 'Gala kết nối cộng đồng EventHub',
                'description' => 'Đêm gặp gỡ cuối mùa với phần networking, trao giải dự án nổi bật và biểu diễn nghệ thuật.',
                'category' => 'Networking',
                'location' => 'Gem Center, TP. Hồ Chí Minh',
                'date_time' => '2026-08-29 18:30:00',
                'capacity' => 300,
                'event_type' => 'Paid',
                'status' => 'published',
                'require_additional_info' => false,
                'custom_form_spec' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
